[theme]
primaryColor="#6C63FF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1A1D23"
textColor="#FFFFFF"
<<<<<<< HEAD
font="sans serif"
=======
font="sans serif"
>>>>>>> 31255239c4a86cea0969126747aabbcd160c2a62
